services:
  - type: web
    name: kandanavolu-paakashala
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_SECRET
        generateValue: true
